# .github/workflows/daily-price-update.yml
name: Daily Gold/Silver Price Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-prices:
    runs-on: ubuntu-latest
    # --- ADD THIS BLOCK HERE ---
    permissions:
      contents: write # This is the crucial permission for pushing changes
    # ---------------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (for node-fetch)
        run: npm install node-fetch

      - name: Run price update script
        id: run_script
        env:
          METALPRICE_API_KEY: ${{ secrets.METALPRICE_API_KEY }}
        run: node ./.github/scripts/fetch-and-save-prices.js

      - name: Commit and Push if prices updated
        if: steps.run_script.outputs.prices_updated == 'true'
        run: |
          echo "Changes detected, committing and pushing..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prices-history.json
          git commit -m "Automated: Update daily gold/silver prices for $(date +%Y-%m-%d)"
          git push
          echo "Successfully pushed changes."
